apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-job-app3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/harshrgith/argocd-jobs.git'
    targetRevision: HEAD
    path: job-app
  destination:
    server: https://kubernetes.default.svc
    namespace: jobs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - PruneLast=true