apiVersion: batch/v1
kind: Job
metadata:
  # Unique name on every sync
  generateName: hello-job-
  namespace: jobs
  labels:
    app.kubernetes.io/name: hello-job
    app.kubernetes.io/part-of: argo-sync
    # Optional: human-readable timestamp
    sync-timestamp: "{{ now | date \"20060102-150405\" }}"
spec:
  ttlSecondsAfterFinished: 86400   # auto-delete after 1 day
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-job
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Hello from Argo CD Job! $(date -u)"