apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: job1
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    app: hello-job
spec:
  template:
    metadata:
      labels:
        app: hello-job
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from Argo CD Job2!"]
      restartPolicy: Never
  backoffLimit: 0