apiVersion: batch/v1
kind: Job
metadata:
  generateName: hello-job
  namespace: jobs
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from Argo CD Job!"]
      restartPolicy: Never
  backoffLimit: 4