apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: jobs
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from Argo CD Job1!"]
      restartPolicy: Never
  backoffLimit: 4