apiVersion: batch/v1
kind: Job
metadata:
  generateName: hello-job-
  namespace: job1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app: hello-job
spec:
  template:
    metadata:
      labels:
        app: hello-job
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from Argo CD Job1!"]
      restartPolicy: Never
  backoffLimit: 0