apiVersion: batch/v1
kind: Job
metadata:
  generateName: hello-job
  namespace: jobs
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceededOrFailed
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from Argo CD Job!"]
      restartPolicy: Never
  backoffLimit: 4